"""The runtimes this deployment offers, defined here rather than upstream.

`BUILTIN_RUNTIMES` in the sandbox library is fifteen recipes the library ships,
and reading the catalogue from there made every change to what *this* product
offers a change to a dependency: a release, a version bump and a pin, to add a
package to one image. Nothing about a runtime needs the library any more - a
`base_image`, a `packages` list and the `setup_commands` that install an apt
layer all reach the service through its allowlist - so what a deployment offers
is a file in this repository.

**One runtime, on purpose.** Eight aliases was a picker, not a product decision:
`prewarm` builds every entry of the allowlist when the service starts, so each
one is a `pip install` at start-up and an image on the host for as long as it is
cached, and an agent asked to open a PDF got whichever alias its spec happened to
name. `workbench` is the one image worth building - two languages, the tools to
navigate a repository, the libraries to read what a user attaches, and a network -
and a deployment that wants a second one adds it here.

One catalogue, two readers, and that is the point:

- the connection dialog's `Default runtime` list, so an operator picks from what
  this product actually ships, before any host has been asked what it allows;
- `SANDBOXD_RUNTIMES`, generated by `agenticos cmd sandbox-runtimes` and asserted
  against the compose files by `tests/test_sandbox_runtime_catalog.py`. That value
  was hand-written JSON in three files, which is three places to forget the trap
  below.

**The trap this encodes.** `SANDBOXD_NETWORK_MODE` is service-wide and the shipped
compose files set it to `none`, so a runtime that installs what a project declares
has to say `bridge` for itself - and an entry written by hand does not inherit
that from anywhere. `needs_network` is that decision, made once where the packages
are, instead of remembered per compose file.

`docs/sandbox.md` is the whole picture - what a session is, what isolates one
organization from another, and how to change this file.
"""

from __future__ import annotations

import json
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, TypeAdapter, model_validator

from app.core.catalog import load

MemLimit = Annotated[str, Field(pattern=r"^\d+[kmg]$")]
"""Docker's own syntax, and the only shape the service accepts."""


class SandboxRuntimeDefinition(BaseModel):
    """One runtime this deployment offers, as two mutually exclusive shapes.

    `image` is ready-made and starts in the time a pull takes. `base_image` is
    built once - `setup_commands` first, then `packages` - and cached after, which
    is what a runtime needs the moment it wants a tool `pip` does not carry.
    """

    alias: str = Field(pattern=r"^[a-z][a-z0-9-]{0,31}$")
    description: str = Field(min_length=1, max_length=200)
    image: str | None = None
    base_image: str | None = None
    setup_commands: list[str] = Field(default_factory=list)
    """Shell run at build time, before the packages - an apt layer, an installer.

    A build has the daemon's network whatever `needs_network` says, so these run
    on a runtime whose sessions have none.
    """

    packages: list[str] = Field(default_factory=list)
    env_vars: dict[str, str] = Field(default_factory=dict)
    """Set in every container on this runtime, and set here rather than per run.

    `MPLBACKEND=Agg` and `PYTHONUTF8=1` are properties of the image, not of an
    agent - a run that has to remember them is a run that will not.
    """

    briefing: list[str] = Field(default_factory=list)
    """What a model is told about this runtime, beyond the derivable.

    The package list, the languages and whether there is a network are read off
    the fields above; these are the sentences that cannot be - what to use
    `lit` for, and the two gaps (no LibreOffice, no compiler) an agent otherwise
    discovers by writing a script that fails. `runtime_briefing` composes the
    two into the paragraph a run's instructions carry.
    """

    mem_limit: MemLimit | None = None
    needs_network: bool = False
    """Whether a *session* on this runtime gets a network at all.

    A build always has the daemon's; this is about the container an agent runs
    in. `true` only where installing at run time is the runtime's purpose -
    everything else has its packages baked in and needs none, which is one less
    way out of a sandbox.
    """

    @model_validator(mode="after")
    def _exactly_one_source(self) -> SandboxRuntimeDefinition:
        """One source, named once.

        A definition carrying both a ready-made image and something to build is
        two runtimes with one alias, and which of them the service builds would
        depend on the order a parser happened to read the keys in.
        """
        if (self.image is None) == (self.base_image is None):
            raise ValueError(f"{self.alias!r} must name exactly one of image or base_image")
        if (self.packages or self.setup_commands) and self.base_image is None:
            raise ValueError(f"{self.alias!r} builds nothing, so it installs nothing")
        return self


CATALOG: tuple[SandboxRuntimeDefinition, ...] = tuple(
    load("sandbox_runtimes.json", TypeAdapter(list[SandboxRuntimeDefinition]))
)
"""Read at import, so a malformed entry stops the deployment rather than
shipping a picker with a hole in it."""


def allowlist_value(*, network_mode: Literal["none", "bridge"] = "none") -> str:
    """The `SANDBOXD_RUNTIMES` value this catalogue describes, as JSON.

    JSON rather than the compact `alias=image` form, because the compact one
    cannot name a package list - which is the whole reason a deployment defines
    its own runtimes instead of taking the library's.

    `network_mode` is the service-wide default the compose file also sets. It is
    an argument rather than a constant so the two cannot disagree: an entry needing
    the network is only given `bridge` explicitly when the service-wide default is
    something else.
    """
    entries: dict[str, Any] = {}
    for runtime in CATALOG:
        entry: dict[str, Any] = {"description": runtime.description}
        if runtime.image is not None:
            entry["image"] = runtime.image
        else:
            entry["runtime"] = {
                "name": runtime.alias,
                "base_image": runtime.base_image,
                "description": runtime.description,
                "setup_commands": runtime.setup_commands,
                "packages": runtime.packages,
                "env_vars": runtime.env_vars,
            }
        if runtime.mem_limit is not None:
            entry["mem_limit"] = runtime.mem_limit
        if runtime.needs_network and network_mode != "bridge":
            entry["network_mode"] = "bridge"
        entries[runtime.alias] = entry
    return json.dumps(entries, separators=(",", ":"), sort_keys=False)


def runtime_briefing(alias: str | None) -> str | None:
    """What a run tells its model about the machine it is about to work on.

    Composed rather than written: the package list and the network come off the
    definition, so a package added to the catalogue reaches the prompt in the same
    edit that reaches the image. Only what cannot be derived is prose, in
    `briefing`.

    Worth having because the alternative is what the product did before: an agent
    asked for a chart wrote `import plotly`, an agent given a PDF wrote its own
    extractor rather than calling `lit`, and both learned otherwise by failing
    inside somebody's request.

    `DEFAULT_INSTRUCTIONS` says a prompt should not list an agent's tools, and
    this does not: which *tools* it has depends on its spec and changes when
    somebody toggles one. What is installed in an image is a fact about the image.

    Args:
        alias: The runtime this run resolved to, or `None` where nothing named
            one - a spec that defers, on a connection that defers too. The first
            entry of the catalogue answers that, because this repository also
            generates the allowlist that makes it the service's own default
            (`tests/test_sandbox_runtime_catalog.py`). A host started with an
            allowlist of its own can therefore be described wrongly here; the
            cost is a package list an agent corrects with one failed import,
            against no briefing at all for every deployment running our compose.

    Returns:
        The paragraph, or `None` for an alias this deployment does not ship -
        where saying nothing is the only honest answer.
    """
    if alias is None:
        runtime = CATALOG[0]
    else:
        found = next((one for one in CATALOG if one.alias == alias), None)
        if found is None:
            return None
        runtime = found

    lines = [
        "## Your workspace",
        "",
        f"You have a container of your own (`{runtime.alias}`) and a shell in it. "
        "Files you write persist for as long as this workspace does, and reading a "
        "file back is how you look at what you produced - including an image.",
        "",
    ]
    lines.extend(f"- {sentence}" for sentence in runtime.briefing)
    if runtime.packages:
        lines.append(
            "- Python packages already installed, so do not install them again: "
            + ", ".join(sorted(runtime.packages))
            + "."
        )
    lines.append(
        "- You have a network, so `uv pip install <package>` and `npm install` work "
        "for anything missing."
        if runtime.needs_network
        else "- There is no network. Nothing can be installed or fetched at run time; "
        "work with what is installed and with the files you were given."
    )
    return "\n".join(lines)
