/**
 * Fetch each catalog server's brand favicon and write them to
 * `src/lib/mcp-logos.generated.ts` as base64 data URIs.
 *
 * The demo "MCP" badge (tool-call-card) reads these so the logo renders in the
 * self-contained HTML export with no network — the badge falls back to the live
 * favicon service only for domains not baked here. Run with: bun run gen:mcp-logos
 */
import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "src", "lib", "mcp-logos.generated.ts");
/**
 * The catalog, which is the backend's.
 *
 * This used to read a table of its own in `src/lib/mcp-catalog.ts` - fourteen servers
 * with hand-written brand domains. Nothing rendered that table and it was deleted, so
 * the domains come from the only catalog the product serves (#446).
 *
 * Keyed on each entry's **URL host**, because that is what `logoDataUri` is looked up
 * with: `tool-steps.ts` derives a step's `logoDomain` from the connection's URL. The
 * deleted table held brand domains instead - `linear.app` where the lookup asks for
 * `mcp.linear.app` - so most baked logos were never found and the badge fell through to
 * the live favicon service (#614). `mcp-catalog.test.ts` holds the invariant: every
 * catalog URL host is a key in the generated map.
 */
const CATALOG = join(here, "..", "..", "backend", "app", "core", "catalog", "mcp_servers.json");

interface CatalogEntry {
  key: string;
  url: string | null;
}

/** The host a server is reached on, or null for one with no URL of its own. */
function hostOf(url: string | null): string | null {
  if (url === null || url === "") return null;
  try {
    return new URL(url).hostname;
  } catch {
    return null;
  }
}

/** Google's favicon service — follows redirects to the actual PNG. */
function faviconUrl(domain: string): string {
  return `https://www.google.com/s2/favicons?sz=128&domain=${encodeURIComponent(domain)}`;
}

async function fetchDataUri(domain: string): Promise<string | null> {
  try {
    const res = await fetch(faviconUrl(domain), { redirect: "follow" });
    if (!res.ok) return null;
    const type = res.headers.get("content-type") ?? "image/png";
    const b64 = Buffer.from(await res.arrayBuffer()).toString("base64");
    return `data:${type};base64,${b64}`;
  } catch {
    return null;
  }
}

/**
 * The logo for `host`, walking up its parent domains on a miss.
 *
 * An MCP endpoint host rarely serves a favicon of its own - `mcp.linear.app`
 * answers 404 where `linear.app` is the brand icon - so a miss retries with one
 * leading label stripped, down to the registrable domain. The map's key stays
 * the host either way, because the host is what the lookup asks with (#614).
 */
async function fetchLogoFor(host: string): Promise<string | null> {
  const labels = host.split(".");
  for (let start = 0; start <= labels.length - 2; start++) {
    const uri = await fetchDataUri(labels.slice(start).join("."));
    if (uri) return uri;
  }
  return null;
}

const entries = JSON.parse(await readFile(CATALOG, "utf8")) as CatalogEntry[];
const hosts = entries.map((entry) => hostOf(entry.url)).filter((host) => host !== null);
const domains = [...new Set(hosts)].sort();
const logos: Record<string, string> = {};
const failed: string[] = [];
for (const domain of domains) {
  const uri = await fetchLogoFor(domain);
  if (uri) {
    logos[domain] = uri;
    console.log(`  ✓ ${domain} (${Math.round(uri.length / 1024)} KB)`);
  } else {
    console.warn(`  ✗ ${domain} — skipped (fetch failed)`);
    failed.push(domain);
  }
}

const body =
  "// AUTO-GENERATED by scripts/gen-mcp-logos.ts — do not edit by hand.\n" +
  '// Brand logos for catalog MCP servers, inlined as data URIs so the "MCP" badge\n' +
  "// shown in demo replays / the self-contained export renders OFFLINE (no external\n" +
  "// favicon fetch). Regenerate with: bun run gen:mcp-logos\n" +
  "export const MCP_LOGOS: Record<string, string> = {\n" +
  Object.entries(logos)
    .map(([d, uri]) => `  ${JSON.stringify(d)}: ${JSON.stringify(uri)},`)
    .join("\n") +
  "\n};\n";

await writeFile(OUT, body, "utf8");
// Formatted here rather than left to the pre-commit hook, so that regenerating
// and running `make lint` in the same breath does not fail on the file this
// script just wrote.
execFileSync("bunx", ["prettier", "--write", "--log-level", "warn", OUT], { stdio: "inherit" });
console.log(`\nWrote ${Object.keys(logos).length} logos → ${OUT}`);

if (failed.length > 0) {
  // A missing logo falls back to the live favicon service at render time, so
  // the export would quietly phone home for that badge. Fail instead of
  // shipping a half-baked file — re-run once the fetch works.
  console.error(`\n${failed.length} logo(s) missing: ${failed.join(", ")} — re-run to fix.`);
  process.exit(1);
}
