"""The schema, as one baseline

Revision ID: 0001_baseline
Revises: None
Create Date: 2026-07-31

Sixty-five revisions collapsed into one, at the only moment it is free: the
repository is one day old, nothing is deployed, and the only databases in existence
are CI's and developers' own.

The chain was not the whole problem. The models and the migrations had drifted, so
`alembic revision --autogenerate` emitted four hundred lines of noise on every run -
a review nobody performs, and the place a real change hides. Every difference was
verified by building both schemas and diffing columns, indexes and constraints:

*Eight columns.* `created_at` was `NOT NULL` in `TimestampMixin` and nullable in the
database on `agents`, `agent_runs`, `agent_versions`, `model_profiles`,
`resource_grants`, `skills`, `skill_resources` and `tool_approvals`. The model was
right - the server default has always filled it - so the database now agrees.

*Four things existed only in the migrations, and the models had to learn them* or
building from the models would have dropped them silently. Three composite indexes:
`agent_runs (organization_id, started_at)` and `(organization_id, started_at,
provider)`, which serve the budget check that runs before every model request, and
`tool_approvals (organization_id, status)`, which serves the approvals queue - a
`status`-only index cannot, because every row in the deployment shares four values.
And a CHECK on `invitations`: a link invitation with `max_uses = 0` is a link that
looks issued and admits nobody.

*Three redundancies are gone.* `invitations.token` and `organizations.slug` each
carried a unique constraint *and* a unique index on the same column - uniqueness is
still enforced, by one index each. `resource_grants` had a plain index duplicating
the columns its unique constraint already covers.

Index names now come from `Base.metadata.naming_convention` (`<table>_<col>_idx`)
instead of the hand-written `ix_*` of the old chain, which was the other half of
autogenerate's noise.

The decisions those revisions recorded are prose now rather than files - the vault
replacing three encryption mechanisms, `users.role` giving way to the permission
catalog, the Tesseract language codes. `docs/` and `CLAUDE.md` cite them by number,
and the numbers resolve in git history before this commit.

**A database already stamped with an old revision cannot read this chain.** Its
`alembic_version` says something like `0066_drop_users_role`, which no longer
exists, and every alembic command answers `Can't locate revision identified by`
rather than doing anything. Two ways out, in order of preference:

    make docker-clean && make dev        # recreate it: the only one that also
                                         # picks up the eight NOT NULL fixes

    uv run --directory backend alembic stamp 0001_baseline
                                         # keep the data, accept that those eight
                                         # columns stay nullable and the three
                                         # redundant indexes stay behind

CI is unaffected - it starts from an empty database every run.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_admin_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=100), nullable=True),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("app_admin_audit_logs_pkey")),
    )
    op.create_index(
        op.f("app_admin_audit_logs_action_idx"), "app_admin_audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("app_admin_audit_logs_actor_user_id_idx"),
        "app_admin_audit_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("app_admin_audit_logs_organization_id_idx"),
        "app_admin_audit_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_app_admin", sa.Boolean(), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("oauth_provider", sa.String(length=32), nullable=True),
        sa.Column("oauth_id", sa.String(length=255), nullable=True),
        sa.Column(
            "notify_budget_alerts", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "notify_approval_requests", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "notify_usage_reports", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_email_idx"), "users", ["email"], unique=True)
    op.create_index(op.f("users_oauth_id_idx"), "users", ["oauth_id"], unique=False)
    op.create_index(op.f("users_oauth_provider_idx"), "users", ["oauth_provider"], unique=False)
    op.create_table(
        "channel_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("platform_user_id", sa.String(length=100), nullable=False),
        sa.Column("platform_username", sa.String(length=100), nullable=True),
        sa.Column("platform_display_name", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("link_code", sa.String(length=10), nullable=True),
        sa.Column("link_code_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("channel_identities_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("channel_identities_pkey")),
        sa.UniqueConstraint(
            "platform", "platform_user_id", name="uq_channel_identity_platform_user"
        ),
    )
    op.create_index(
        op.f("channel_identities_platform_idx"), "channel_identities", ["platform"], unique=False
    )
    op.create_index(
        op.f("channel_identities_platform_user_id_idx"),
        "channel_identities",
        ["platform_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("channel_identities_user_id_idx"), "channel_identities", ["user_id"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("is_personal", sa.Boolean(), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("monthly_budget_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "monthly_budget_usd IS NULL OR monthly_budget_usd > 0",
            name=op.f("organizations_ck_organization_budget_positive_check"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("organizations_created_by_user_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("organizations_pkey")),
    )
    op.create_index(
        op.f("organizations_created_by_user_id_idx"),
        "organizations",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("organizations_is_personal_idx"), "organizations", ["is_personal"], unique=False
    )
    op.create_index(op.f("organizations_slug_idx"), "organizations", ["slug"], unique=True)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=255), nullable=False),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("sessions_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sessions_pkey")),
    )
    op.create_index(
        op.f("sessions_refresh_token_hash_idx"), "sessions", ["refresh_token_hash"], unique=False
    )
    op.create_index(op.f("sessions_user_id_idx"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_slash_commands",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_slash_commands_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_slash_commands_pkey")),
        sa.UniqueConstraint("user_id", "name", name="uq_user_slash_commands_user_name"),
    )
    op.create_index(
        op.f("user_slash_commands_user_id_idx"), "user_slash_commands", ["user_id"], unique=False
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "draft_spec",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("agents_ck_agent_status_check"),
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'team', 'org')",
            name=op.f("agents_ck_agent_visibility_check"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("agents_created_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("agents_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("agents_owner_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agents_pkey")),
        sa.UniqueConstraint("organization_id", "slug", name="uq_agent_org_slug"),
    )
    op.create_index(op.f("agents_organization_id_idx"), "agents", ["organization_id"], unique=False)
    op.create_index(op.f("agents_owner_user_id_idx"), "agents", ["owner_user_id"], unique=False)
    op.create_index(op.f("agents_slug_idx"), "agents", ["slug"], unique=False)
    op.create_index(op.f("agents_status_idx"), "agents", ["status"], unique=False)
    op.create_table(
        "channel_bots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("token_encrypted", sa.String(length=1000), nullable=False),
        sa.Column("secret_key_version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("webhook_mode", sa.Boolean(), nullable=False),
        sa.Column("webhook_url", sa.String(length=500), nullable=True),
        sa.Column("api_base_url", sa.String(length=500), nullable=True),
        sa.Column("webhook_secret", sa.String(length=255), nullable=True),
        sa.Column("slack_signing_secret_encrypted", sa.String(length=1000), nullable=True),
        sa.Column("slack_app_token_encrypted", sa.String(length=1000), nullable=True),
        sa.Column("access_policy", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("channel_bots_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("channel_bots_pkey")),
    )
    op.create_index(
        op.f("channel_bots_organization_id_idx"), "channel_bots", ["organization_id"], unique=False
    )
    op.create_index(op.f("channel_bots_platform_idx"), "channel_bots", ["platform"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("conversations_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("conversations_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("conversations_pkey")),
    )
    op.create_index(
        op.f("conversations_organization_id_idx"),
        "conversations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("conversations_user_id_idx"), "conversations", ["user_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("email_domain", sa.String(length=255), nullable=True),
        sa.Column("invited_by_user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_user_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "email IS NOT NULL OR max_uses IS NULL OR max_uses > 0",
            name=op.f("invitations_ck_invitation_max_uses_positive_check"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"], ["users.id"], name=op.f("invitations_accepted_by_user_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"], ["users.id"], name=op.f("invitations_invited_by_user_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("invitations_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("invitations_pkey")),
    )
    op.create_index(op.f("invitations_email_idx"), "invitations", ["email"], unique=False)
    op.create_index(
        op.f("invitations_organization_id_idx"), "invitations", ["organization_id"], unique=False
    )
    op.create_index(op.f("invitations_status_idx"), "invitations", ["status"], unique=False)
    op.create_index(op.f("invitations_token_idx"), "invitations", ["token"], unique=True)
    op.create_index(
        "uq_pending_invitation",
        "invitations",
        ["organization_id", "email"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "mcp_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("scope", sa.String(length=8), nullable=False),
        sa.Column("catalog_key", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("auth_token", sa.Text(), nullable=True),
        sa.Column("secret_key_version", sa.Integer(), nullable=False),
        sa.Column("allowed_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("auth_type", sa.String(length=16), nullable=False),
        sa.Column("oauth_state", sa.String(length=128), nullable=True),
        sa.Column("oauth_payload", sa.Text(), nullable=True),
        sa.Column("oauth_pending_payload", sa.Text(), nullable=True),
        sa.Column("last_status", sa.String(length=16), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "scope <> 'org' OR organization_id IS NOT NULL",
            name=op.f("mcp_connections_ck_mcp_connection_org_scope_has_org_check"),
        ),
        sa.CheckConstraint(
            "scope <> 'org' OR user_id IS NULL",
            name=op.f("mcp_connections_ck_mcp_connection_org_scope_has_no_user_check"),
        ),
        sa.CheckConstraint(
            "scope <> 'user' OR user_id IS NOT NULL",
            name=op.f("mcp_connections_ck_mcp_connection_user_scope_has_user_check"),
        ),
        sa.CheckConstraint(
            "scope IN ('user', 'org')", name=op.f("mcp_connections_ck_mcp_connection_scope_check")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("mcp_connections_created_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("mcp_connections_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("mcp_connections_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("mcp_connections_pkey")),
        sa.UniqueConstraint("user_id", "name", name="uq_mcp_connections_user_name"),
    )
    op.create_index(
        op.f("mcp_connections_oauth_state_idx"), "mcp_connections", ["oauth_state"], unique=False
    )
    op.create_index(
        op.f("mcp_connections_organization_id_idx"),
        "mcp_connections",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("mcp_connections_scope_idx"), "mcp_connections", ["scope"], unique=False)
    op.create_index(
        op.f("mcp_connections_user_id_idx"), "mcp_connections", ["user_id"], unique=False
    )
    op.create_index(
        "uq_mcp_connections_org_name",
        "mcp_connections",
        ["organization_id", "name"],
        unique=True,
        postgresql_where=sa.text("scope = 'org'"),
    )
    op.create_table(
        "organization_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("invited_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("organization_members_invited_by_user_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("organization_members_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("organization_members_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("organization_members_pkey")),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_org_member"),
    )
    op.create_index(
        "ix_org_member_org_role", "organization_members", ["organization_id", "role"], unique=False
    )
    op.create_index(
        op.f("organization_members_organization_id_idx"),
        "organization_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("organization_members_user_id_idx"), "organization_members", ["user_id"], unique=False
    )
    op.create_table(
        "organization_secrets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("sealed_secret", sa.String(), nullable=False),
        sa.Column("hint", sa.String(length=8), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "visibility <> 'private' OR owner_user_id IS NOT NULL",
            name=op.f("organization_secrets_ck_secret_private_needs_owner_check"),
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'team', 'org')",
            name=op.f("organization_secrets_ck_secret_visibility_check"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("organization_secrets_created_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("organization_secrets_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("organization_secrets_owner_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("organization_secrets_pkey")),
        sa.UniqueConstraint("organization_id", "name", name="uq_organization_secret_org_name"),
    )
    op.create_index(
        op.f("organization_secrets_organization_id_idx"),
        "organization_secrets",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("organization_secrets_owner_user_id_idx"),
        "organization_secrets",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("organization_secrets_purpose_idx"), "organization_secrets", ["purpose"], unique=False
    )
    op.create_index(
        op.f("organization_secrets_visibility_idx"),
        "organization_secrets",
        ["visibility"],
        unique=False,
    )
    op.create_table(
        "resource_grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("subject_user_id", sa.UUID(), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "level IN ('read', 'use', 'edit')",
            name=op.f("resource_grants_ck_resource_grant_level_check"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("resource_grants_created_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("resource_grants_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_user_id"],
            ["users.id"],
            name=op.f("resource_grants_subject_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("resource_grants_pkey")),
        sa.UniqueConstraint(
            "resource_type", "resource_id", "subject_user_id", name="uq_resource_grant_subject"
        ),
    )
    op.create_index(
        op.f("resource_grants_organization_id_idx"),
        "resource_grants",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("resource_grants_resource_id_idx"), "resource_grants", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("resource_grants_resource_type_idx"),
        "resource_grants",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("resource_grants_subject_user_id_idx"),
        "resource_grants",
        ["subject_user_id"],
        unique=False,
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "visibility IN ('private', 'team', 'org')",
            name=op.f("skills_ck_skill_visibility_check"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("skills_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("skills_owner_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("skills_pkey")),
        sa.UniqueConstraint("organization_id", "name", name="uq_skill_org_name"),
    )
    op.create_index(op.f("skills_organization_id_idx"), "skills", ["organization_id"], unique=False)
    op.create_index(op.f("skills_owner_user_id_idx"), "skills", ["owner_user_id"], unique=False)
    op.create_table(
        "sync_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("connector_type", sa.String(length=20), nullable=False),
        sa.Column("collection_name", sa.String(length=255), nullable=True),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("sync_mode", sa.String(length=20), nullable=False),
        sa.Column("schedule_minutes", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_status", sa.String(length=20), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("sync_sources_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sync_sources_pkey")),
    )
    op.create_index(
        op.f("sync_sources_collection_name_idx"), "sync_sources", ["collection_name"], unique=False
    )
    op.create_index(
        op.f("sync_sources_organization_id_idx"), "sync_sources", ["organization_id"], unique=False
    )
    op.create_table(
        "agent_embeds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("public_key", sa.String(length=64), nullable=False),
        sa.Column("auth_mode", sa.String(length=16), nullable=False),
        sa.Column("jwt_secret_encrypted", sa.String(length=1000), nullable=True),
        sa.Column(
            "allowed_origins",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "theme", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "auth_mode <> 'jwt' OR jwt_secret_encrypted IS NOT NULL",
            name=op.f("agent_embeds_ck_embed_jwt_needs_secret_check"),
        ),
        sa.CheckConstraint(
            "auth_mode IN ('public', 'jwt')", name=op.f("agent_embeds_ck_embed_auth_mode_check")
        ),
        sa.CheckConstraint(
            "rate_limit_per_minute > 0",
            name=op.f("agent_embeds_ck_embed_rate_limit_positive_check"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("agent_embeds_agent_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("agent_embeds_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("agent_embeds_owner_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_embeds_pkey")),
    )
    op.create_index(op.f("agent_embeds_agent_id_idx"), "agent_embeds", ["agent_id"], unique=False)
    op.create_index(
        op.f("agent_embeds_organization_id_idx"), "agent_embeds", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("agent_embeds_public_key_idx"), "agent_embeds", ["public_key"], unique=True
    )
    op.create_table(
        "agent_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("published_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("agent_versions_agent_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("agent_versions_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("agent_versions_published_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_versions_pkey")),
        sa.UniqueConstraint("agent_id", "version", name="uq_agent_version_number"),
    )
    op.create_index(
        op.f("agent_versions_agent_id_idx"), "agent_versions", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("agent_versions_organization_id_idx"),
        "agent_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "channel_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("identity_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("platform_chat_id", sa.String(length=100), nullable=False),
        sa.Column("chat_type", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["channel_bots.id"],
            name=op.f("channel_sessions_bot_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("channel_sessions_conversation_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["channel_identities.id"],
            name=op.f("channel_sessions_identity_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("channel_sessions_pkey")),
        sa.UniqueConstraint("bot_id", "platform_chat_id", name="uq_channel_session_bot_chat"),
    )
    op.create_index(
        op.f("channel_sessions_bot_id_idx"), "channel_sessions", ["bot_id"], unique=False
    )
    op.create_index(
        op.f("channel_sessions_conversation_id_idx"),
        "channel_sessions",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("channel_sessions_identity_id_idx"), "channel_sessions", ["identity_id"], unique=False
    )
    op.create_index(
        op.f("channel_sessions_platform_chat_id_idx"),
        "channel_sessions",
        ["platform_chat_id"],
        unique=False,
    )
    op.create_table(
        "conversation_shares",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("shared_by", sa.UUID(), nullable=False),
        sa.Column("shared_with", sa.UUID(), nullable=True),
        sa.Column("share_token", sa.String(length=64), nullable=True),
        sa.Column("permission", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("conversation_shares_conversation_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shared_by"],
            ["users.id"],
            name=op.f("conversation_shares_shared_by_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shared_with"],
            ["users.id"],
            name=op.f("conversation_shares_shared_with_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("conversation_shares_pkey")),
        sa.UniqueConstraint("conversation_id", "shared_with", name="uq_share_conv_user"),
        sa.UniqueConstraint("share_token", name=op.f("conversation_shares_share_token_key")),
    )
    op.create_index(
        op.f("conversation_shares_conversation_id_idx"),
        "conversation_shares",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("conversation_shares_shared_with_idx"),
        "conversation_shares",
        ["shared_with"],
        unique=False,
    )
    op.create_table(
        "knowledge_bases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("collection_name", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "ingestion_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("embedding_dim", sa.Integer(), nullable=False),
        sa.Column("embedding_secret_id", sa.UUID(), nullable=True),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "scope <> 'org' OR organization_id IS NOT NULL",
            name=op.f("knowledge_bases_ck_knowledge_bases_org_scope_has_org_check"),
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'team', 'org')",
            name=op.f("knowledge_bases_ck_knowledge_bases_visibility_check"),
        ),
        sa.ForeignKeyConstraint(
            ["embedding_secret_id"],
            ["organization_secrets.id"],
            name=op.f("knowledge_bases_embedding_secret_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("knowledge_bases_organization_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("knowledge_bases_owner_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("knowledge_bases_pkey")),
    )
    op.create_index(
        op.f("knowledge_bases_collection_name_idx"),
        "knowledge_bases",
        ["collection_name"],
        unique=False,
    )
    op.create_index(
        op.f("knowledge_bases_organization_id_idx"),
        "knowledge_bases",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("knowledge_bases_owner_user_id_idx"),
        "knowledge_bases",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(op.f("knowledge_bases_scope_idx"), "knowledge_bases", ["scope"], unique=False)
    op.create_table(
        "model_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("secret_id", sa.UUID(), nullable=True),
        sa.Column("base_url", sa.String(length=512), nullable=True),
        sa.Column(
            "params", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("allow_byo", sa.Boolean(), nullable=False),
        sa.Column(
            "fallback_profile_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("model_profiles_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["secret_id"],
            ["organization_secrets.id"],
            name=op.f("model_profiles_secret_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("model_profiles_pkey")),
        sa.UniqueConstraint("organization_id", "label", name="uq_model_profile_org_label"),
    )
    op.create_index(
        op.f("model_profiles_organization_id_idx"),
        "model_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "skill_resources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("skill_resources_skill_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("skill_resources_pkey")),
        sa.UniqueConstraint("skill_id", "name", name="uq_skill_resource_name"),
    )
    op.create_index(
        op.f("skill_resources_skill_id_idx"), "skill_resources", ["skill_id"], unique=False
    )
    op.create_table(
        "sync_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("collection_name", sa.String(length=255), nullable=False),
        sa.Column("sync_source_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("total_files", sa.Integer(), nullable=False),
        sa.Column("ingested", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["sync_source_id"],
            ["sync_sources.id"],
            name=op.f("sync_logs_sync_source_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sync_logs_pkey")),
    )
    op.create_index(
        op.f("sync_logs_collection_name_idx"), "sync_logs", ["collection_name"], unique=False
    )
    op.create_table(
        "agent_environments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("logfire_token_secret_id", sa.UUID(), nullable=True),
        sa.Column("service_name", sa.String(length=128), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("agent_environments_agent_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("agent_environments_created_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["logfire_token_secret_id"],
            ["organization_secrets.id"],
            name=op.f("agent_environments_logfire_token_secret_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("agent_environments_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["agent_versions.id"],
            name=op.f("agent_environments_version_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_environments_pkey")),
        sa.UniqueConstraint("agent_id", "name", name="uq_environment_agent_name"),
    )
    op.create_index(
        op.f("agent_environments_agent_id_idx"), "agent_environments", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("agent_environments_organization_id_idx"),
        "agent_environments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "uq_environment_agent_default",
        "agent_environments",
        ["agent_id"],
        unique=True,
        postgresql_where=sa.text("is_default IS true"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("thinking", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("agent_version_id", sa.UUID(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("messages_agent_id_fkey"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_versions.id"],
            name=op.f("messages_agent_version_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("messages_conversation_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
    )
    op.create_index(op.f("messages_agent_id_idx"), "messages", ["agent_id"], unique=False)
    op.create_index(
        op.f("messages_conversation_id_idx"), "messages", ["conversation_id"], unique=False
    )
    op.create_table(
        "rag_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_name", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("filesize", sa.Integer(), nullable=False),
        sa.Column("filetype", sa.String(length=20), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("vector_document_id", sa.String(length=255), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "ingestion_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("ingestion_override", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("image_description_model", sa.String(length=255), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("knowledge_base_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("rag_documents_knowledge_base_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("rag_documents_organization_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("rag_documents_pkey")),
    )
    op.create_index(
        op.f("rag_documents_collection_name_idx"),
        "rag_documents",
        ["collection_name"],
        unique=False,
    )
    op.create_index(
        op.f("rag_documents_knowledge_base_id_idx"),
        "rag_documents",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(
        op.f("rag_documents_organization_id_idx"),
        "rag_documents",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "agent_exposures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("surface", sa.String(length=16), nullable=False),
        sa.Column("channel_bot_id", sa.UUID(), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "surface IN ('slack', 'telegram', 'mattermost')",
            name=op.f("agent_exposures_ck_exposure_surface_check"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("agent_exposures_agent_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["channel_bot_id"],
            ["channel_bots.id"],
            name=op.f("agent_exposures_channel_bot_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("agent_exposures_created_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["agent_environments.id"],
            name=op.f("agent_exposures_environment_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("agent_exposures_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_exposures_pkey")),
        sa.UniqueConstraint("agent_id", "channel_bot_id", name="uq_exposure_agent_bot"),
    )
    op.create_index(
        op.f("agent_exposures_agent_id_idx"), "agent_exposures", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("agent_exposures_channel_bot_id_idx"),
        "agent_exposures",
        ["channel_bot_id"],
        unique=False,
    )
    op.create_index(
        op.f("agent_exposures_organization_id_idx"),
        "agent_exposures",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "chat_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("file_type", sa.String(length=20), nullable=False),
        sa.Column("parsed_content", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("chat_files_message_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("chat_files_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_files_pkey")),
    )
    op.create_index(op.f("chat_files_user_id_idx"), "chat_files", ["user_id"], unique=False)
    op.create_table(
        "ingestion_spend",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("rag_document_id", sa.UUID(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("cost_is_partial", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("ingestion_spend_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rag_document_id"],
            ["rag_documents.id"],
            name=op.f("ingestion_spend_rag_document_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ingestion_spend_pkey")),
    )
    op.create_index(
        "ix_ingestion_spend_org_created",
        "ingestion_spend",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "message_ratings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("rating IN (1, -1)", name=op.f("message_ratings_ck_rating_value_check")),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("message_ratings_message_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("message_ratings_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("message_ratings_pkey")),
        sa.UniqueConstraint("message_id", "user_id", name="uq_message_user_rating"),
    )
    op.create_index(
        op.f("message_ratings_message_id_idx"), "message_ratings", ["message_id"], unique=False
    )
    op.create_index(
        op.f("message_ratings_user_id_idx"), "message_ratings", ["user_id"], unique=False
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("tool_call_id", sa.String(length=100), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("tool_calls_message_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tool_calls_pkey")),
    )
    op.create_index(op.f("tool_calls_message_id_idx"), "tool_calls", ["message_id"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("agent_version_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("exposure_id", sa.UUID(), nullable=True),
        sa.Column("environment_id", sa.UUID(), nullable=True),
        sa.Column("surface", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("model_label", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("secret_id", sa.UUID(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("cost_is_partial", sa.Boolean(), nullable=False),
        sa.Column("logfire_trace_id", sa.String(length=64), nullable=True),
        sa.Column("paused_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("agent_runs_agent_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_versions.id"],
            name=op.f("agent_runs_agent_version_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("agent_runs_conversation_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["agent_environments.id"],
            name=op.f("agent_runs_environment_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["exposure_id"],
            ["agent_exposures.id"],
            name=op.f("agent_runs_exposure_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("agent_runs_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["secret_id"],
            ["organization_secrets.id"],
            name=op.f("agent_runs_secret_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("agent_runs_user_id_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_runs_pkey")),
    )
    op.create_index(op.f("agent_runs_agent_id_idx"), "agent_runs", ["agent_id"], unique=False)
    op.create_index(
        op.f("agent_runs_organization_id_idx"), "agent_runs", ["organization_id"], unique=False
    )
    op.create_index(op.f("agent_runs_provider_idx"), "agent_runs", ["provider"], unique=False)
    op.create_index(op.f("agent_runs_secret_id_idx"), "agent_runs", ["secret_id"], unique=False)
    op.create_index(op.f("agent_runs_status_idx"), "agent_runs", ["status"], unique=False)
    op.create_index(op.f("agent_runs_user_id_idx"), "agent_runs", ["user_id"], unique=False)
    op.create_index(
        "ix_agent_runs_org_started", "agent_runs", ["organization_id", "started_at"], unique=False
    )
    op.create_index(
        "ix_agent_runs_org_started_provider",
        "agent_runs",
        ["organization_id", "started_at", "provider"],
        unique=False,
    )
    op.create_table(
        "tool_approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("tool_id", sa.String(length=64), nullable=False),
        sa.Column(
            "tool_args",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_by_user_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'expired')",
            name=op.f("tool_approvals_ck_tool_approval_status_check"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("tool_approvals_agent_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("tool_approvals_decided_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("tool_approvals_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("tool_approvals_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tool_approvals_pkey")),
    )
    op.create_index(
        "ix_tool_approvals_org_status",
        "tool_approvals",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("tool_approvals_organization_id_idx"),
        "tool_approvals",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("tool_approvals_run_id_idx"), "tool_approvals", ["run_id"], unique=False)
    op.create_index(op.f("tool_approvals_status_idx"), "tool_approvals", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("tool_approvals_status_idx"), table_name="tool_approvals")
    op.drop_index(op.f("tool_approvals_run_id_idx"), table_name="tool_approvals")
    op.drop_index(op.f("tool_approvals_organization_id_idx"), table_name="tool_approvals")
    op.drop_index("ix_tool_approvals_org_status", table_name="tool_approvals")
    op.drop_table("tool_approvals")
    op.drop_index("ix_agent_runs_org_started_provider", table_name="agent_runs")
    op.drop_index("ix_agent_runs_org_started", table_name="agent_runs")
    op.drop_index(op.f("agent_runs_user_id_idx"), table_name="agent_runs")
    op.drop_index(op.f("agent_runs_status_idx"), table_name="agent_runs")
    op.drop_index(op.f("agent_runs_secret_id_idx"), table_name="agent_runs")
    op.drop_index(op.f("agent_runs_provider_idx"), table_name="agent_runs")
    op.drop_index(op.f("agent_runs_organization_id_idx"), table_name="agent_runs")
    op.drop_index(op.f("agent_runs_agent_id_idx"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("tool_calls_message_id_idx"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("message_ratings_user_id_idx"), table_name="message_ratings")
    op.drop_index(op.f("message_ratings_message_id_idx"), table_name="message_ratings")
    op.drop_table("message_ratings")
    op.drop_index("ix_ingestion_spend_org_created", table_name="ingestion_spend")
    op.drop_table("ingestion_spend")
    op.drop_index(op.f("chat_files_user_id_idx"), table_name="chat_files")
    op.drop_table("chat_files")
    op.drop_index(op.f("agent_exposures_organization_id_idx"), table_name="agent_exposures")
    op.drop_index(op.f("agent_exposures_channel_bot_id_idx"), table_name="agent_exposures")
    op.drop_index(op.f("agent_exposures_agent_id_idx"), table_name="agent_exposures")
    op.drop_table("agent_exposures")
    op.drop_index(op.f("rag_documents_organization_id_idx"), table_name="rag_documents")
    op.drop_index(op.f("rag_documents_knowledge_base_id_idx"), table_name="rag_documents")
    op.drop_index(op.f("rag_documents_collection_name_idx"), table_name="rag_documents")
    op.drop_table("rag_documents")
    op.drop_index(op.f("messages_conversation_id_idx"), table_name="messages")
    op.drop_index(op.f("messages_agent_id_idx"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "uq_environment_agent_default",
        table_name="agent_environments",
        postgresql_where=sa.text("is_default IS true"),
    )
    op.drop_index(op.f("agent_environments_organization_id_idx"), table_name="agent_environments")
    op.drop_index(op.f("agent_environments_agent_id_idx"), table_name="agent_environments")
    op.drop_table("agent_environments")
    op.drop_index(op.f("sync_logs_collection_name_idx"), table_name="sync_logs")
    op.drop_table("sync_logs")
    op.drop_index(op.f("skill_resources_skill_id_idx"), table_name="skill_resources")
    op.drop_table("skill_resources")
    op.drop_index(op.f("model_profiles_organization_id_idx"), table_name="model_profiles")
    op.drop_table("model_profiles")
    op.drop_index(op.f("knowledge_bases_scope_idx"), table_name="knowledge_bases")
    op.drop_index(op.f("knowledge_bases_owner_user_id_idx"), table_name="knowledge_bases")
    op.drop_index(op.f("knowledge_bases_organization_id_idx"), table_name="knowledge_bases")
    op.drop_index(op.f("knowledge_bases_collection_name_idx"), table_name="knowledge_bases")
    op.drop_table("knowledge_bases")
    op.drop_index(op.f("conversation_shares_shared_with_idx"), table_name="conversation_shares")
    op.drop_index(op.f("conversation_shares_conversation_id_idx"), table_name="conversation_shares")
    op.drop_table("conversation_shares")
    op.drop_index(op.f("channel_sessions_platform_chat_id_idx"), table_name="channel_sessions")
    op.drop_index(op.f("channel_sessions_identity_id_idx"), table_name="channel_sessions")
    op.drop_index(op.f("channel_sessions_conversation_id_idx"), table_name="channel_sessions")
    op.drop_index(op.f("channel_sessions_bot_id_idx"), table_name="channel_sessions")
    op.drop_table("channel_sessions")
    op.drop_index(op.f("agent_versions_organization_id_idx"), table_name="agent_versions")
    op.drop_index(op.f("agent_versions_agent_id_idx"), table_name="agent_versions")
    op.drop_table("agent_versions")
    op.drop_index(op.f("agent_embeds_public_key_idx"), table_name="agent_embeds")
    op.drop_index(op.f("agent_embeds_organization_id_idx"), table_name="agent_embeds")
    op.drop_index(op.f("agent_embeds_agent_id_idx"), table_name="agent_embeds")
    op.drop_table("agent_embeds")
    op.drop_index(op.f("sync_sources_organization_id_idx"), table_name="sync_sources")
    op.drop_index(op.f("sync_sources_collection_name_idx"), table_name="sync_sources")
    op.drop_table("sync_sources")
    op.drop_index(op.f("skills_owner_user_id_idx"), table_name="skills")
    op.drop_index(op.f("skills_organization_id_idx"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("resource_grants_subject_user_id_idx"), table_name="resource_grants")
    op.drop_index(op.f("resource_grants_resource_type_idx"), table_name="resource_grants")
    op.drop_index(op.f("resource_grants_resource_id_idx"), table_name="resource_grants")
    op.drop_index(op.f("resource_grants_organization_id_idx"), table_name="resource_grants")
    op.drop_table("resource_grants")
    op.drop_index(op.f("organization_secrets_visibility_idx"), table_name="organization_secrets")
    op.drop_index(op.f("organization_secrets_purpose_idx"), table_name="organization_secrets")
    op.drop_index(op.f("organization_secrets_owner_user_id_idx"), table_name="organization_secrets")
    op.drop_index(
        op.f("organization_secrets_organization_id_idx"), table_name="organization_secrets"
    )
    op.drop_table("organization_secrets")
    op.drop_index(op.f("organization_members_user_id_idx"), table_name="organization_members")
    op.drop_index(
        op.f("organization_members_organization_id_idx"), table_name="organization_members"
    )
    op.drop_index("ix_org_member_org_role", table_name="organization_members")
    op.drop_table("organization_members")
    op.drop_index(
        "uq_mcp_connections_org_name",
        table_name="mcp_connections",
        postgresql_where=sa.text("scope = 'org'"),
    )
    op.drop_index(op.f("mcp_connections_user_id_idx"), table_name="mcp_connections")
    op.drop_index(op.f("mcp_connections_scope_idx"), table_name="mcp_connections")
    op.drop_index(op.f("mcp_connections_organization_id_idx"), table_name="mcp_connections")
    op.drop_index(op.f("mcp_connections_oauth_state_idx"), table_name="mcp_connections")
    op.drop_table("mcp_connections")
    op.drop_index(
        "uq_pending_invitation",
        table_name="invitations",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("invitations_token_idx"), table_name="invitations")
    op.drop_index(op.f("invitations_status_idx"), table_name="invitations")
    op.drop_index(op.f("invitations_organization_id_idx"), table_name="invitations")
    op.drop_index(op.f("invitations_email_idx"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("conversations_user_id_idx"), table_name="conversations")
    op.drop_index(op.f("conversations_organization_id_idx"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("channel_bots_platform_idx"), table_name="channel_bots")
    op.drop_index(op.f("channel_bots_organization_id_idx"), table_name="channel_bots")
    op.drop_table("channel_bots")
    op.drop_index(op.f("agents_status_idx"), table_name="agents")
    op.drop_index(op.f("agents_slug_idx"), table_name="agents")
    op.drop_index(op.f("agents_owner_user_id_idx"), table_name="agents")
    op.drop_index(op.f("agents_organization_id_idx"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("user_slash_commands_user_id_idx"), table_name="user_slash_commands")
    op.drop_table("user_slash_commands")
    op.drop_index(op.f("sessions_user_id_idx"), table_name="sessions")
    op.drop_index(op.f("sessions_refresh_token_hash_idx"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("organizations_slug_idx"), table_name="organizations")
    op.drop_index(op.f("organizations_is_personal_idx"), table_name="organizations")
    op.drop_index(op.f("organizations_created_by_user_id_idx"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("channel_identities_user_id_idx"), table_name="channel_identities")
    op.drop_index(op.f("channel_identities_platform_user_id_idx"), table_name="channel_identities")
    op.drop_index(op.f("channel_identities_platform_idx"), table_name="channel_identities")
    op.drop_table("channel_identities")
    op.drop_index(op.f("users_oauth_provider_idx"), table_name="users")
    op.drop_index(op.f("users_oauth_id_idx"), table_name="users")
    op.drop_index(op.f("users_email_idx"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("app_admin_audit_logs_organization_id_idx"), table_name="app_admin_audit_logs"
    )
    op.drop_index(op.f("app_admin_audit_logs_actor_user_id_idx"), table_name="app_admin_audit_logs")
    op.drop_index(op.f("app_admin_audit_logs_action_idx"), table_name="app_admin_audit_logs")
    op.drop_table("app_admin_audit_logs")
    # ### end Alembic commands ###
