"""What order the turns of a conversation were written in.

`created_at` could not answer it. Both rows of one turn - the question and the
answer - are written inside a single transaction, and `func.now()` is the
*transaction's* start time in Postgres, so the two carry the same timestamp to
the microsecond. `ORDER BY created_at` then has nothing to break the tie with and
the planner returns whichever it likes, which is why the answer appearing above
the question looked intermittent. A tie-break on `id` is no help either: the ids
are `uuid4`.

So an ordinal, allocated from one deployment-wide identity rather than a counter
per conversation. A per-conversation counter is `MAX(ordinal) + 1`, which two
transactions read the same answer to - and the loser of that race either violates
a unique constraint (losing the transcript, since the write is wrapped in a
savepoint that swallows it) or writes a duplicate and reintroduces the tie. An
identity column has neither problem: it is monotonic in insert order, gaps are
harmless, and a conversation's own rows come back in the order they were written.

Backfilled in three steps rather than one: adding a `NOT NULL` identity column
rewrites the table filling values in *physical* order, which is not the order the
rows were written. So the values are assigned explicitly by `created_at`, then
the sequence is moved past them, then the column is tightened. Ties among
existing rows - the very rows this fixes - break on `id`, which is arbitrary but
stable, and no better answer exists for turns already written.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0027_message_ordinal"
down_revision: str | Sequence[str] | None = "0026_message_author"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("messages", sa.Column("ordinal", sa.BigInteger(), nullable=True))
    op.execute(
        """
        UPDATE messages AS m
        SET ordinal = numbered.position
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS position
            FROM messages
        ) AS numbered
        WHERE m.id = numbered.id
        """
    )
    op.execute("ALTER TABLE messages ALTER COLUMN ordinal SET NOT NULL")
    op.execute(
        "ALTER TABLE messages ALTER COLUMN ordinal "
        "ADD GENERATED BY DEFAULT AS IDENTITY "
        "(START WITH 1 INCREMENT BY 1)"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('messages', 'ordinal'), "
        "COALESCE((SELECT MAX(ordinal) FROM messages), 0) + 1, false)"
    )
    # Read one way only: this conversation's rows, in order. The index leads on
    # the conversation for that reason rather than on the ordinal, which is
    # globally unique and so tells a lookup nothing on its own.
    op.create_index(
        "messages_conversation_id_ordinal_idx",
        "messages",
        ["conversation_id", "ordinal"],
    )


def downgrade() -> None:
    op.drop_index("messages_conversation_id_ordinal_idx", table_name="messages")
    op.drop_column("messages", "ordinal")
