"""Make the app-admin audit trail tamper-evident.

`app_admin_audit_logs` is the record of every privileged action, and the app-admin
bypass story in `docs/governance.md` leans on it - but a row is just a row, and an
operator with the database could rewrite or delete one and leave nothing that says
so. This gives each entry a place in a per-organization hash chain: `entry_hash`
over the entry's canonical fields with the previous entry's hash folded in, so
editing, reordering, inserting or interior-deleting an entry diverges every hash
after it - which `agenticos cmd audit-verify` recomputes and reports. Detection,
not prevention, and blind to the newest entries or a whole chain being dropped
(#1622).

Three columns, backfilled in the order that makes each safe:

- `seq` is the deployment-wide order the chain is walked in. `created_at` cannot be
  it - Postgres `now()` is transaction-stable, so two entries one transaction
  writes share a timestamp, and a `uuid4` id cannot break the tie. It is filled by
  `ROW_NUMBER() OVER (ORDER BY created_at, id)` and only then turned into an
  identity column and tightened, exactly as `0027_message_ordinal` did and for the
  same reason: adding a `NOT NULL` identity column outright fills it in physical
  order, not write order.
- `prev_hash`/`entry_hash` are backfilled per organization in `seq` order, walking
  each chain from its start. `chain_hash` is imported from `app.core.audit` rather
  than reimplemented, the way `0013_seal_webhook_secret` imports the vault: a second
  copy of the hash is a second thing to keep in step, and if it drifts the verifier
  calls an untouched trail broken.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.core.audit import chain_hash

revision: str = "0079_audit_hash_chain"
down_revision: str | Sequence[str] | None = "0078_local_services"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_BACKFILL_SELECT = """
    SELECT id, actor_user_id, impersonator_user_id, organization_id, action,
           target_type, target_id, details, ip_address, created_at
    FROM app_admin_audit_logs
    ORDER BY seq
"""
_BACKFILL_UPDATE = (
    "UPDATE app_admin_audit_logs SET prev_hash = :prev_hash, entry_hash = :entry_hash "
    "WHERE id = :id"
)


def upgrade() -> None:
    op.add_column("app_admin_audit_logs", sa.Column("seq", sa.BigInteger(), nullable=True))
    op.add_column(
        "app_admin_audit_logs", sa.Column("prev_hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "app_admin_audit_logs", sa.Column("entry_hash", sa.String(length=64), nullable=True)
    )

    op.execute(
        """
        UPDATE app_admin_audit_logs AS a
        SET seq = numbered.position
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS position
            FROM app_admin_audit_logs
        ) AS numbered
        WHERE a.id = numbered.id
        """
    )

    # Walk each organization's chain from its start, linking each entry to the one
    # before it. Reading in `seq` order and bucketing by organization keeps every
    # chain in the order `record_audit` would have written it. NULL is the
    # deployment-wide chain (the expiry sweep, operator shell commands) and is one
    # bucket like any other.
    bind = op.get_bind()
    heads: dict[object, str | None] = {}
    for row in bind.execute(sa.text(_BACKFILL_SELECT)):
        prev_hash = heads.get(row.organization_id)
        entry_hash = chain_hash(
            prev_hash=prev_hash,
            actor_user_id=row.actor_user_id,
            impersonator_user_id=row.impersonator_user_id,
            organization_id=row.organization_id,
            action=row.action,
            target_type=row.target_type,
            target_id=row.target_id,
            details=row.details,
            ip_address=row.ip_address,
            created_at=row.created_at,
        )
        bind.execute(
            sa.text(_BACKFILL_UPDATE),
            {"prev_hash": prev_hash, "entry_hash": entry_hash, "id": row.id},
        )
        heads[row.organization_id] = entry_hash

    op.execute("ALTER TABLE app_admin_audit_logs ALTER COLUMN seq SET NOT NULL")
    op.execute(
        "ALTER TABLE app_admin_audit_logs ALTER COLUMN seq "
        "ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('app_admin_audit_logs', 'seq'), "
        "COALESCE((SELECT MAX(seq) FROM app_admin_audit_logs), 0) + 1, false)"
    )
    op.create_unique_constraint("app_admin_audit_logs_seq_key", "app_admin_audit_logs", ["seq"])

    op.execute("ALTER TABLE app_admin_audit_logs ALTER COLUMN entry_hash SET NOT NULL")

    op.create_index(
        "app_admin_audit_logs_org_seq_idx",
        "app_admin_audit_logs",
        ["organization_id", "seq"],
    )


def downgrade() -> None:
    op.drop_index("app_admin_audit_logs_org_seq_idx", table_name="app_admin_audit_logs")
    op.drop_constraint("app_admin_audit_logs_seq_key", "app_admin_audit_logs", type_="unique")
    op.drop_column("app_admin_audit_logs", "entry_hash")
    op.drop_column("app_admin_audit_logs", "prev_hash")
    op.drop_column("app_admin_audit_logs", "seq")
