"""Durable execution: workflow runs, node runs, attempts, the dispatch outbox,
the event stream and resolved resource references (#1788).

Six new tables, all `organization_id`-scoped. `workflow_runs` is the run
itself and the only one with a self-referencing pair
(`root_run_id`/`causation_run_id`) - #1785's cycle-protection columns, added
now rather than backfilled later, since retrofitting them onto a table
already holding runs is a migration nobody wants. `node_runs` is one node's
position in a run; `node_attempts` is append-only, one row per try, never
updated after it reaches a terminal status - the same reason `agent_runs`
never overwrites a row. `dispatch_outbox` is a transactional outbox: its
partial unique index on live (`pending`/`claimed`) rows is what makes "at
most one live dispatch per node run" a database fact rather than a
convention every writer has to remember; its partial indexes on `pending`
and `claimed` rows serve the poller's scan and the reconciler's lease scans,
and `submitted_at` is what keeps the poll from resubmitting a row it already
handed to a worker. `workflow_events` is an
append-only stream with a per-run monotonic `seq`. `resource_refs` holds the
`FileRef`/`TableIORef` bindings a run resolved once at start.

Revision ID: 0095_workflow_runs
Revises: 0093_workflows
Create Date: 2026-09-23
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0095_workflow_runs"
down_revision: str | Sequence[str] | None = "0093_workflows"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_version_id", sa.UUID(), nullable=True),
        sa.Column("draft_graph_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("triggered_by", sa.String(length=16), nullable=False),
        sa.Column("execution_principal_user_id", sa.UUID(), nullable=True),
        sa.Column("budget_limit", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("spent_cost", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("cost_is_partial", sa.Boolean(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_event_seq", sa.BigInteger(), nullable=False),
        sa.Column("paused_reason", sa.String(length=20), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("root_run_id", sa.UUID(), nullable=False),
        sa.Column("causation_run_id", sa.UUID(), nullable=True),
        sa.Column("visited_trigger_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "mode IN ('real', 'test')", name=op.f("workflow_runs_ck_workflow_run_mode_check")
        ),
        sa.CheckConstraint(
            "paused_reason IS NULL OR paused_reason IN ('approval', 'external_event', 'retry_backoff')",
            name=op.f("workflow_runs_ck_workflow_run_paused_reason_check"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'waiting_approval', 'waiting_retry', 'needs_attention', 'budget_exceeded', 'cancelled', 'failed', 'succeeded')",
            name=op.f("workflow_runs_ck_workflow_run_status_check"),
        ),
        sa.CheckConstraint(
            "triggered_by IN ('api', 'websocket', 'webhook', 'chat', 'schedule', 'table_created')",
            name=op.f("workflow_runs_ck_workflow_run_triggered_by_check"),
        ),
        sa.CheckConstraint(
            "(workflow_version_id IS NULL) != (draft_graph_snapshot IS NULL)",
            name=op.f("workflow_runs_ck_workflow_run_graph_source_xor_check"),
        ),
        sa.CheckConstraint("depth >= 0", name=op.f("workflow_runs_ck_workflow_run_depth_check")),
        sa.CheckConstraint(
            "spent_cost >= 0", name=op.f("workflow_runs_ck_workflow_run_spent_cost_check")
        ),
        sa.ForeignKeyConstraint(
            ["causation_run_id"],
            ["workflow_runs.id"],
            name=op.f("workflow_runs_causation_run_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["execution_principal_user_id"],
            ["users.id"],
            name=op.f("workflow_runs_execution_principal_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("workflow_runs_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["root_run_id"], ["workflow_runs.id"], name=op.f("workflow_runs_root_run_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("workflow_runs_workflow_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("workflow_runs_workflow_version_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("workflow_runs_pkey")),
    )
    op.create_index(
        "ix_workflow_run_org_status", "workflow_runs", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("workflow_runs_execution_principal_user_id_idx"),
        "workflow_runs",
        ["execution_principal_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("workflow_runs_root_run_id_idx"), "workflow_runs", ["root_run_id"], unique=False
    )
    op.create_index(op.f("workflow_runs_status_idx"), "workflow_runs", ["status"], unique=False)
    op.create_index(
        op.f("workflow_runs_workflow_id_idx"), "workflow_runs", ["workflow_id"], unique=False
    )
    op.create_table(
        "resource_refs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("ref", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('file', 'table')", name=op.f("resource_refs_ck_resource_ref_kind_check")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("resource_refs_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("resource_refs_workflow_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("resource_refs_pkey")),
    )
    op.create_index(
        op.f("resource_refs_organization_id_idx"),
        "resource_refs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("resource_refs_workflow_run_id_idx"),
        "resource_refs",
        ["workflow_run_id"],
        unique=False,
    )
    op.create_table(
        "node_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("node_instance_id", sa.UUID(), nullable=False),
        sa.Column("scope_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("waiting_reason", sa.String(length=20), nullable=True),
        sa.Column("resume_token", sa.Text(), nullable=True),
        sa.Column("waiting_agent_run_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'waiting', 'needs_attention', 'succeeded', 'failed', 'skipped', 'cancelled')",
            name=op.f("node_runs_ck_node_run_status_check"),
        ),
        sa.CheckConstraint(
            "waiting_reason IS NULL OR waiting_reason IN ('approval', 'external_event', 'retry_backoff')",
            name=op.f("node_runs_ck_node_run_waiting_reason_check"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("node_runs_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["waiting_agent_run_id"],
            ["agent_runs.id"],
            name=op.f("node_runs_waiting_agent_run_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("node_runs_workflow_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("node_runs_pkey")),
        sa.UniqueConstraint(
            "workflow_run_id", "node_instance_id", "scope_path", name="uq_node_run_identity"
        ),
    )
    op.create_index(
        op.f("node_runs_organization_id_idx"), "node_runs", ["organization_id"], unique=False
    )
    op.create_index(op.f("node_runs_status_idx"), "node_runs", ["status"], unique=False)
    op.create_index(
        op.f("node_runs_waiting_agent_run_id_idx"),
        "node_runs",
        ["waiting_agent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("node_runs_workflow_run_id_idx"), "node_runs", ["workflow_run_id"], unique=False
    )
    op.create_table(
        "dispatch_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("node_run_id", sa.UUID(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_by", sa.UUID(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'claimed', 'done', 'cancelled')",
            name=op.f("dispatch_outbox_ck_dispatch_outbox_status_check"),
        ),
        sa.ForeignKeyConstraint(
            ["node_run_id"],
            ["node_runs.id"],
            name=op.f("dispatch_outbox_node_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("dispatch_outbox_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("dispatch_outbox_workflow_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("dispatch_outbox_pkey")),
    )
    op.create_index(
        op.f("dispatch_outbox_organization_id_idx"),
        "dispatch_outbox",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("dispatch_outbox_workflow_run_id_idx"),
        "dispatch_outbox",
        ["workflow_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_dispatch_outbox_pending_claim",
        "dispatch_outbox",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_dispatch_outbox_claimed_lease",
        "dispatch_outbox",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'claimed'"),
    )
    op.create_index("ix_dispatch_outbox_node_run", "dispatch_outbox", ["node_run_id"], unique=False)
    op.create_index(
        "uq_dispatch_outbox_live_node_run",
        "dispatch_outbox",
        ["node_run_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'claimed')"),
    )
    op.create_table(
        "node_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("node_run_id", sa.UUID(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("retry_guarantee", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("cost_is_partial", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "retry_guarantee IS NULL OR retry_guarantee IN ('none', 'idempotent', 'at_least_once')",
            name=op.f("node_attempts_ck_node_attempt_retry_guarantee_check"),
        ),
        sa.CheckConstraint(
            "status IN ('in_flight', 'completed', 'failed', 'uncertain')",
            name=op.f("node_attempts_ck_node_attempt_status_check"),
        ),
        sa.CheckConstraint(
            "attempt_no >= 1", name=op.f("node_attempts_ck_node_attempt_number_check")
        ),
        sa.CheckConstraint("cost >= 0", name=op.f("node_attempts_ck_node_attempt_cost_check")),
        sa.ForeignKeyConstraint(
            ["node_run_id"],
            ["node_runs.id"],
            name=op.f("node_attempts_node_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("node_attempts_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("node_attempts_pkey")),
        sa.UniqueConstraint("node_run_id", "attempt_no", name="uq_node_attempt_number"),
    )
    op.create_index(
        op.f("node_attempts_node_run_id_idx"), "node_attempts", ["node_run_id"], unique=False
    )
    op.create_index(
        "ix_node_attempt_in_flight",
        "node_attempts",
        ["node_run_id"],
        unique=False,
        postgresql_where=sa.text("status = 'in_flight'"),
    )
    op.create_index(
        op.f("node_attempts_organization_id_idx"),
        "node_attempts",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "workflow_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("node_run_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_run_id"],
            ["node_runs.id"],
            name=op.f("workflow_events_node_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("workflow_events_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("workflow_events_workflow_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("workflow_events_pkey")),
        sa.UniqueConstraint("workflow_run_id", "seq", name="uq_workflow_event_seq"),
    )
    op.create_index(
        op.f("workflow_events_organization_id_idx"),
        "workflow_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("workflow_events_workflow_run_id_idx"),
        "workflow_events",
        ["workflow_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("workflow_events_workflow_run_id_idx"), table_name="workflow_events")
    op.drop_index(op.f("workflow_events_organization_id_idx"), table_name="workflow_events")
    op.drop_table("workflow_events")
    op.drop_index(op.f("node_attempts_organization_id_idx"), table_name="node_attempts")
    op.drop_index(
        "ix_node_attempt_in_flight",
        table_name="node_attempts",
        postgresql_where=sa.text("status = 'in_flight'"),
    )
    op.drop_index(op.f("node_attempts_node_run_id_idx"), table_name="node_attempts")
    op.drop_table("node_attempts")
    op.drop_index(
        "uq_dispatch_outbox_live_node_run",
        table_name="dispatch_outbox",
        postgresql_where=sa.text("status IN ('pending', 'claimed')"),
    )
    op.drop_index("ix_dispatch_outbox_node_run", table_name="dispatch_outbox")
    op.drop_index(
        "ix_dispatch_outbox_claimed_lease",
        table_name="dispatch_outbox",
        postgresql_where=sa.text("status = 'claimed'"),
    )
    op.drop_index(
        "ix_dispatch_outbox_pending_claim",
        table_name="dispatch_outbox",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("dispatch_outbox_workflow_run_id_idx"), table_name="dispatch_outbox")
    op.drop_index(op.f("dispatch_outbox_organization_id_idx"), table_name="dispatch_outbox")
    op.drop_table("dispatch_outbox")
    op.drop_index(op.f("node_runs_workflow_run_id_idx"), table_name="node_runs")
    op.drop_index(op.f("node_runs_waiting_agent_run_id_idx"), table_name="node_runs")
    op.drop_index(op.f("node_runs_status_idx"), table_name="node_runs")
    op.drop_index(op.f("node_runs_organization_id_idx"), table_name="node_runs")
    op.drop_table("node_runs")
    op.drop_index(op.f("resource_refs_workflow_run_id_idx"), table_name="resource_refs")
    op.drop_index(op.f("resource_refs_organization_id_idx"), table_name="resource_refs")
    op.drop_table("resource_refs")
    op.drop_index(op.f("workflow_runs_workflow_id_idx"), table_name="workflow_runs")
    op.drop_index(op.f("workflow_runs_status_idx"), table_name="workflow_runs")
    op.drop_index(op.f("workflow_runs_root_run_id_idx"), table_name="workflow_runs")
    op.drop_index(op.f("workflow_runs_execution_principal_user_id_idx"), table_name="workflow_runs")
    op.drop_index("ix_workflow_run_org_status", table_name="workflow_runs")
    op.drop_table("workflow_runs")
    # ### end Alembic commands ###
