"use client";

import {
  Input,
  OptionalSetting,
  OptionalSlider,
  PROVIDER_DEFAULT_KEY,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui";
import type { ModelSettingsSpec } from "@/types/agents";
import { useTranslations } from "next-intl";

interface ModelSettingsFormProps {
  value: ModelSettingsSpec;
  onChange: (value: ModelSettingsSpec) => void;
  disabled?: boolean;
}

export { PROVIDER_DEFAULT_KEY };

/**
 * Where a slider sits before anybody has chosen anything.
 *
 * A range input has no empty state, so an untouched one has to point
 * *somewhere*. It points at the value most providers use, and says
 * `PROVIDER_DEFAULT_KEY` beside itself so the position is never read as a choice.
 */
const RESTING: Record<"temperature" | "top_p", number> = { temperature: 1, top_p: 1 };

/**
 * The model settings an agent author may set, and the state of never having set
 * one.
 *
 * Hand-written rather than generated by `SchemaForm`, for two reasons that only
 * apply here. The generated form renders a capability's `config_schema`, which
 * the API publishes; `model_settings` is a field of the spec itself and has no
 * schema on the wire, so generating it would mean inventing an endpoint to
 * describe five known fields. And the controls are not in that form's subset: a
 * temperature is a slider, "how many tools at once" is three-valued, and every
 * one of them needs to show *unset* as a first-class state, which a number input
 * showing an empty box does not do convincingly.
 *
 * That unset state is the whole point. A field nobody touched must not be sent:
 * reasoning models reject `temperature` however it is spelled, so a Builder that
 * helpfully filled in `0.7` would break every agent pointed at one. Clearing a
 * control removes the key rather than writing `null`.
 */
export function ModelSettingsForm({ value, onChange, disabled }: ModelSettingsFormProps) {
  const t = useTranslations("agents");
  const tu = useTranslations("ui");
  /** Remove the key rather than store an empty value - see the note above. */
  const set = <K extends keyof ModelSettingsSpec>(key: K, next: ModelSettingsSpec[K]) => {
    const updated = { ...value };
    if (next === undefined) {
      delete updated[key];
    } else {
      updated[key] = next;
    }
    onChange(updated);
  };

  return (
    <div className="space-y-6">
      <OptionalSlider
        id="model-temperature"
        label={t("temperature")}
        description={t("howVariedAnswerNear")}
        max={2}
        value={value.temperature}
        resting={RESTING.temperature}
        disabled={disabled}
        onChange={(next) => set("temperature", next)}
      />

      <OptionalSlider
        id="model-top-p"
        label={t("topP")}
        description={t("considerOnlyMostLikely")}
        max={1}
        value={value.top_p}
        resting={RESTING.top_p}
        disabled={disabled}
        onChange={(next) => set("top_p", next)}
      />

      <div className="grid gap-6 sm:grid-cols-2">
        <OptionalSetting
          htmlFor="model-max-tokens"
          label={t("maxTokens")}
          description={t("longestAnswerModelMay")}
          onReset={value.max_tokens === undefined ? undefined : () => set("max_tokens", undefined)}
          disabled={disabled}
        >
          <Input
            id="model-max-tokens"
            type="number"
            min={1}
            max={200000}
            step={1}
            value={value.max_tokens ?? ""}
            disabled={disabled}
            placeholder={tu(PROVIDER_DEFAULT_KEY)}
            onChange={(event) => set("max_tokens", asNumber(event.target.value))}
          />
        </OptionalSetting>

        <OptionalSetting
          htmlFor="model-timeout"
          label={t("timeoutSeconds")}
          description={t("howLongOneModel")}
          onReset={value.timeout === undefined ? undefined : () => set("timeout", undefined)}
          disabled={disabled}
        >
          <Input
            id="model-timeout"
            type="number"
            min={1}
            max={600}
            step={1}
            value={value.timeout ?? ""}
            disabled={disabled}
            placeholder={tu(PROVIDER_DEFAULT_KEY)}
            onChange={(event) => set("timeout", asNumber(event.target.value))}
          />
        </OptionalSetting>
      </div>

      <OptionalSetting
        htmlFor="model-parallel-tool-calls"
        label={t("toolCalls")}
        description={t("runningThemOneAt")}
        disabled={disabled}
      >
        {/*
          A switch would be wrong here: it has two positions and this has three,
          and the third is the one the agent is in until somebody decides
          otherwise. Not every provider implements it, so "provider default" is
          not a synonym for either answer.
        */}
        <Select
          value={parallelToolCalls(value.parallel_tool_calls)}
          disabled={disabled}
          onValueChange={(next) =>
            set("parallel_tool_calls", next === "default" ? undefined : next === "parallel")
          }
        >
          <SelectTrigger id="model-parallel-tool-calls">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="default">{tu(PROVIDER_DEFAULT_KEY)}</SelectItem>
            <SelectItem value="parallel">{t("severalAtOnce")}</SelectItem>
            <SelectItem value="sequential">{t("oneAtTime")}</SelectItem>
          </SelectContent>
        </Select>
      </OptionalSetting>
    </div>
  );
}

/** The stored tri-state as the select's own vocabulary. */
function parallelToolCalls(allowed: boolean | undefined): string {
  if (allowed === undefined) return "default";
  return allowed ? "parallel" : "sequential";
}

/** Empty is unset, which is not zero - the same reading `SchemaForm` uses. */
function asNumber(raw: string): number | undefined {
  return raw === "" ? undefined : Number(raw);
}
