#!/usr/bin/env python3
"""Derive the product mark from the mascot, so the two can never disagree.

`docs/assets/amigo.svg` is the drawing; everything else is a crop of it. The mark
is Amigo's head and hat squared off - rows 0 to 9 of the sprite, centred in a
16x16 box so it drops into an icon slot without letterboxing.

Three surfaces need that crop, and they cannot share a file: MkDocs wants a path,
and the console draws it inside a `next/og` image where only a data URI survives.
So this writes all three from the one drawing, and
`backend/tests/test_amigo_mark.py` fails when a re-run would change them.

Usage::

    python3 scripts/gen_amigo_head.py          # rewrite the derived files
    python3 scripts/gen_amigo_head.py --check  # exit 1 if they are stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
MASCOT = ROOT / "docs/assets/amigo.svg"
MARK_SVG = ROOT / "docs/assets/amigo-head.svg"
MARK_TS = ROOT / "frontend/src/lib/amigo-head.generated.ts"

#: Sprite rows that make up the head: the hat, the face and the shoulders under it.
HEAD_ROWS = 9
#: Where those rows sit once centred in a square box.
TOP_PAD = 3

#: A plain pixel. The eyelids the idle animation blinks carry a `class` and are
#: deliberately not matched - they are animation, not drawing.
RECT = re.compile(r'<rect x="(\d+)" y="(\d+)" width="(\d+)" height="(\d+)" fill="(#[0-9a-f]{6})"/>')


def read_pixels() -> list[tuple[int, int, int, int, str]]:
    """The mascot's pixels, in paint order."""
    return [
        (int(x), int(y), int(w), int(h), fill)
        for x, y, w, h, fill in RECT.findall(MASCOT.read_text())
    ]


def build_mark() -> str:
    """The head crop, as a standalone square SVG."""
    rows = [p for p in read_pixels() if p[1] <= HEAD_ROWS]
    body = "\n".join(
        f'  <rect x="{x}" y="{y + TOP_PAD}" width="{w}" height="{h}" fill="{fill}"/>'
        for x, y, w, h, fill in rows
    )
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="64" height="64"'
        ' shape-rendering="crispEdges" role="img" aria-label="AgenticOS">\n'
        f"  <title>AgenticOS</title>\n{body}\n</svg>\n"
    )


def build_module(mark: str) -> str:
    """The same crop as a data URI, for the surfaces that cannot load a file."""
    # Percent-encoded rather than base64: this is read by a client component and by
    # Satori inside `next/og`, and neither `btoa` nor `Buffer` exists in both. The
    # indentation is collapsed first - it is a third of the encoded length, and
    # nothing reads this string as source.
    uri = "data:image/svg+xml," + quote(" ".join(mark.split()), safe="")
    return (
        "// Generated by scripts/gen_amigo_head.py - do not edit.\n"
        "// The mark is a crop of docs/assets/amigo.svg; change the drawing, then re-run.\n\n"
        "/** Amigo's head and hat, squared off: the built-in mark, as a data URI. */\n"
        f'export const AMIGO_HEAD_DATA_URI =\n  "{uri}";\n'
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report staleness instead of writing")
    args = parser.parse_args()

    mark = build_mark()
    module = build_module(mark)
    stale = [
        path
        for path, want in ((MARK_SVG, mark), (MARK_TS, module))
        if not path.exists() or path.read_text() != want
    ]
    if args.check:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1 if stale else 0
    MARK_SVG.write_text(mark)
    MARK_TS.write_text(module)
    for path in stale:
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
